version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - confluent
  kafka1:
    image: confluentinc/cp-kafka:5.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:19092,EXTERNAL://kafkaserver:9092
      KAFKA_LISTENERS: INTERNAL://:19092,EXTERNAL://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    restart: always
    networks:
      - confluent
    volumes:
      - /var/logs/kafka1:/var/lib/kafka

  kafka2:
    image: confluentinc/cp-kafka:5.0.1
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:19093,EXTERNAL://kafkaserver:9093
      KAFKA_LISTENERS: INTERNAL://:19093,EXTERNAL://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    restart: always
    networks:
      - confluent  
    volumes:
      - /var/logs/kafka2:/var/lib/kafka

  kafka3:
    image: confluentinc/cp-kafka:5.0.1
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:19094,EXTERNAL://kafkaserver:9094
      KAFKA_LISTENERS: INTERNAL://:19094,EXTERNAL://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    restart: always
    networks:
      - confluent
    volumes:
      - /var/logs/kafka3:/var/lib/kafka

networks:
    confluent:

